baseURL = 'https://jmurabe.github.io/lifelog-blog/'
defaultContentLanguage = 'ja'
title = 'murave LifeLog'
theme = "PaperMod"
pagination.pagerSize = 5

[params.homeInfoParams]
  Title = "é›‘è¨˜ãƒ»é£Ÿäº‹ãƒ»ãƒ•ã‚£ãƒƒãƒˆãƒã‚¹ ğŸ“"
  Content = "muraveã®ãƒ¡ãƒ¢ã§ã™ã€‚Blogã¨ã„ã†ã‚ˆã‚Šã¯LifeLogã‹ãªã¨ã€‚"

[params]
  author = "murave"
  socialIcons = [
    { name = 'x', url = 'https://x.com/murave' },
    { name = 'github', url = 'https://github.com/jmurabe' },
  ]
  ShowReadingTime = true
  ShowToc = true
  TocOpen = true
  ShowPostNavLinks = true
  disableScrollToTop = false
  dateFormat = "2006-01-02(Mon)"

[menu]
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/Search/"
  weight = 5
[[menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 10
[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 20
[[menu.main]]
  identifier = "archives"
  name = "Archives"
  url = "/archives/"
  weight = 30

[outputs]
home = ["HTML", "JSON"]
